[package]
  cjc-version = "1.0.0"
  name = "metis"
  description = "nothing here"
  version = "1.0.0"
  target-dir = ""
  src-dir = ""
  output-type = "executable"
  compile-option = "-Woff unused --cfg \"ohos=false,enable_tree_sitter=true,enable_cl100k_tokenizer=true\" "
  override-compile-option = ""
  link-option = ""

[profile.test]
  parallel = 1
  no-progress = true
  no-color = true

[profile.test.env]
  cjHeapSize = { value = "64MB", splice-type = "replace" }

[dependencies]
  magic = { path = "${MAGIC_PATH}" }

[ffi.c]
  rawinput = { path="./ffi/" }
  signature_extractor = { path = "./ffi/" }

[target.x86_64-unknown-linux-gnu.bin-dependencies]
  path-option = ["${MAGIC_PATH}/libs/cangjie-stdx-linux-x64-1.0.0.1/linux_x86_64_llvm/dynamic/stdx"]

[target.x86_64-unknown-windows-gnu.bin-dependencies]
  path-option = ["${MAGIC_PATH}/libs/cangjie-stdx-windows-x64-1.0.0.1/windows_x86_64_llvm/dynamic/stdx"]

[target.x86_64-w64-mingw32.bin-dependencies]
  path-option = ["${MAGIC_PATH}/libs/cangjie-stdx-windows-x64-1.0.0.1/windows_x86_64_llvm/dynamic/stdx"]

[target.aarch64-unknown-linux-gnu.bin-dependencies]
  path-option = ["${MAGIC_PATH}/libs/cangjie-stdx-linux-aarch64-1.0.0.1/linux_aarch64_llvm/dynamic/stdx"]

[target.aarch64-apple-darwin.bin-dependencies]
  path-option = ["${MAGIC_PATH}/libs/cangjie-stdx-mac-aarch64-1.0.0.1/darwin_aarch64_llvm/dynamic/stdx"]
